package paasaathai

// The consonant classes
type ConsonantClass int

const (
	UndefinedClass ConsonantClass = 0
	HighClass                     = 1
	MidClass                      = 2
	LowClass                      = 3
)

func (s ConsonantClass) String() string {
	switch s {
	case HighClass:
		return "HighClass"
	case MidClass:
		return "MidClass"
	case LowClass:
		return "LowClass"
	default:
		return "UndefinedClass"
	}
}

var HighClassRunes = NewSetFromSlice[rune]([]rune{
	THAI_CHARACTER_KHO_KHAI,
	THAI_CHARACTER_KHO_KHUAT,
	THAI_CHARACTER_CHO_CHING,
	THAI_CHARACTER_THO_THAN,
	THAI_CHARACTER_THO_THUNG,
	THAI_CHARACTER_PHO_PHUNG,
	THAI_CHARACTER_FO_FA,
	THAI_CHARACTER_SO_SALA,
	THAI_CHARACTER_SO_RUSI,
	THAI_CHARACTER_SO_SUA,
	THAI_CHARACTER_HO_HIP,
})

var MidClassRunes = NewSetFromSlice[rune]([]rune{
	THAI_CHARACTER_KO_KAI,
	THAI_CHARACTER_CHO_CHAN,
	THAI_CHARACTER_DO_CHADA,
	THAI_CHARACTER_TO_PATAK,
	THAI_CHARACTER_DO_DEK,
	THAI_CHARACTER_TO_TAO,
	THAI_CHARACTER_BO_BAIMAI,
	THAI_CHARACTER_PO_PLA,
	THAI_CHARACTER_O_ANG,
})

var LowClassRunes = NewSetFromSlice[rune]([]rune{
	THAI_CHARACTER_KHO_KHWAI,
	THAI_CHARACTER_KHO_KHON,
	THAI_CHARACTER_KHO_RAKHANG,
	THAI_CHARACTER_NGO_NGU,
	THAI_CHARACTER_CHO_CHANG,
	THAI_CHARACTER_SO_SO,
	THAI_CHARACTER_CHO_CHOE,
	THAI_CHARACTER_YO_YING,
	THAI_CHARACTER_THO_NANGMONTHO,
	THAI_CHARACTER_THO_PHUTHAO,
	THAI_CHARACTER_NO_NEN,
	THAI_CHARACTER_THO_THAHAN,
	THAI_CHARACTER_THO_THONG,
	THAI_CHARACTER_NO_NU,
	THAI_CHARACTER_PHO_PHAN,
	THAI_CHARACTER_FO_FAN,
	THAI_CHARACTER_PHO_SAMPHAO,
	THAI_CHARACTER_MO_MA,
	THAI_CHARACTER_YO_YAK,
	THAI_CHARACTER_RO_RUA,
	THAI_CHARACTER_RU,
	THAI_CHARACTER_LO_LING,
	THAI_CHARACTER_LU,
	THAI_CHARACTER_WO_WAEN,
	THAI_CHARACTER_LO_CHULA,
	THAI_CHARACTER_HO_NOKHUK,
})
